### ISSUE TITLE
[Feather Request] Option to remove the trailing zero in cpu temp reading

### ISSUE THREAD

**Issue by yipinghuang1991** [nwg-piotr/psuinfo#1]
CPU temp reading is always a whole number.
A switch to toggle the ".0" would be awesome.
(Or just remove the ".0")

**Comment by nwg-piotr** [comment]
I'm currently working on the second package, containing non-psutil-based scripts ([details here](https://github.com/nwg-piotr/tint2-executors/tree/master/arch-package)), and I'd like to avoid multiplying arguments. I think stripping ".0" makes sense. Will be done tonight.

**Comment by nwg-piotr** [comment]
Done in 1.0-1 version. See [README](https://github.com/nwg-piotr/psuinfo/blob/master/README.md) for more info. Thanks for feedback!
