### ISSUE TITLE
Installation on Debian

### ISSUE THREAD

**Issue by pvpscript** [nwg-piotr/psuinfo#2]
How would I install it on Debian?

**Comment by nwg-piotr** [comment]
Well, you could do it manually:

```
$ git clone https://github.com/nwg-piotr/psuinfo.git
$ cd psuinfo
$ sudo cp psuinfo /usr/bin
$ sudo mkdir /usr/share/psuinfo
$ sudo cp icons/*.svg /usr/share/psuinfo
$ sudo cp configs/*.tint2rc /usr/share/tint2
```

Make sure the `/usr/bin/psuinfo` file is executable.

![psuinfo-debian](https://user-images.githubusercontent.com/20579136/63893052-74768c80-c9e9-11e9-8a8b-3a730ce85f3a.png)

In the picture I skipped installing sample config files, since my one and only Debian runs dwm, not Openbox.

**Comment by nwg-piotr** [comment]
By the way: @Head-on-a-Stick - would you mind making a Debian package?

**Comment by pvpscript** [comment]
Thanks! It works!
It doesn't show icons in the tint2 bar, though. The following error is prompted:

```
***** Imlib2 Developer Warning ***** :
	This program is calling the Imlib call:

	imlib_image_set_never_changes_on_disk();

	With the parameter:

	image

	being NULL. Please fix your program.

```

When I run the command on a terminal, the first line shows the icon's location, which I made sure it was correct.

**Comment by nwg-piotr** [comment]
My script only produces the text output you see in the terminal, and tint2 is due to makes use of it. Does your tint2 display other svg icons? Is your imlib2 library installed and up to date?

**Comment by pvpscript** [comment]
Yes, my tint2 can display icons and my imlib2 is installed, according to apt.
I just tested it again and noticed that the icon was shown for a split second, but then it disappeared and I got the same error.

**Comment by nwg-piotr** [comment]
Anything wrong with the executor itself? Have you tried any of the sample configs?

**Comment by pvpscript** [comment]
Welp... I actually didn't tried the samples, because if I did I would've figured out...
Just changed **execp_continuous** to **0** and it worked!

**Comment by nwg-piotr** [comment]
Tint2 is quite difficult to configure yet powerful panel. I've been on Sway for about half a year, and tint2 doesn't work here. Having added some own stuff, I made myself comfortable on the py3status panel, but I still miss svg icons.
